// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpaivunovmsynkmvkybw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwYWl2dW5vdm1zeW5rbXZreWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NTc1MjIsImV4cCI6MjA1NzAzMzUyMn0.9MHFEv_nlmYcbk-bfdPu-YCDFzHRUr-tRbqK7Ijm0p8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);